---
sudo: false
language: python

# LOL!
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django111-wagtail112

    - python: 3.5
      env: TOXENV=py35-django111-wagtail112
    - python: 3.5
      env: TOXENV=py35-django111-wagtail230
    - python: 3.5
      env: TOXENV=py35-django210-wagtail230
    - python: 3.5
      env: TOXENV=py35-django220-wagtail250

    - python: 3.6
      env: TOXENV=py36-django111-wagtail112
    - python: 3.6
      env: TOXENV=py36-django111-wagtail230
    - python: 3.6
      env: TOXENV=py36-django210-wagtail230
    - python: 3.6
      env: TOXENV=py36-django220-wagtail250

  allow_failures:
    - python: 3.6
      env: TOXENV=lint


install:
  - pip install tox codecov


script:
  - tox


after_success:
  - tox -e coverage-report
  - codecov
